library(changepoint)
library(ggplot2)
library(dplyr)
library(plotly)
setwd("/srv/shiny-server/pilot-anapp/edc_analysis_acid")
tsDT <- read.csv("H3PO4_CONCENT_X.csv",header = TRUE)
names(tsDT) <- c("count","mea")
tsDTcptVar <- changepoint::cpt.var(tsDT[,2])
plot(tsDTcptVar)
tsDTcptMean <- changepoint::cpt.mean(tsDT[,2])
plot(tsDTcptMean)

tsDTcptMeanvar <- changepoint::cpt.meanvar(tsDT[,2])
plot(tsDTcptMeanvar)

# multiple change point
#cptMP <-cpt.var(tsDT[,2],penalty="Manual",pen.value="2*log(n)",method="BinSeg",Q=20,class=TRUE)
#cptMP <-cpt.var(tsDT[,2],penalty="Manual",pen.value="2*log(n)",method="PELT",Q=20,class=TRUE)
#cptMP <-cpt.meanvar(tsDT[,2],method='BinSeg',Q=100)
#cptMP1 <-cpt.var(diff(tsDT[,2]),penalty="Manual",pen.value="80*log10(n)",test.stat="CSS",method='BinSeg',Q=100)
cptMP1 <-cpt.meanvar(diff(tsDT[,2]),test.stat="Gamma")
ncpts(cptMP1)
cptMP1 <- as.data.frame(cpts.ts(cptMP1))
names(cptMP1) <- c("count")
cptMP1 <- dplyr::inner_join(tsDT,cptMP1,by="count")

cptMP2 <-cpt.var(diff(tsDT[,2]),penalty="Manual",pen.value="80*log10(n)",method='BinSeg',Q=100)
ncpts(cptMP2)
cptMP2 <- as.data.frame(cpts.ts(cptMP2))
names(cptMP2) <- c("count")
cptMP2 <- dplyr::inner_join(tsDT,cptMP2,by="count")

a <- ggplot() + geom_point(aes(x=tsDT[,1],y=tsDT[,2]))
a <- a + geom_jitter(aes(x=cptMP1[,1],y=cptMP1[,2]),colour = 'red')
a <- a + geom_jitter(aes(x=cptMP2[,1],y=cptMP2[,2]),colour = 'green')
ggplotly(a)
